ALTER TABLE "Cycle" ADD COLUMN "ordre" INTEGER NOT NULL DEFAULT 0;

UPDATE "Cycle"
SET "ordre" = CASE "code"
  WHEN 'PRESCOLAIRE' THEN 1
  WHEN 'PRIMAIRE' THEN 2
  WHEN 'COLLEGE' THEN 3
  WHEN 'LYCEE' THEN 4
  ELSE 0
END;

CREATE INDEX "Cycle_tenantId_ordre_idx" ON "Cycle"("tenantId", "ordre");